Support jwt auth
ionorg/ion pull request #303
Opened 2020-06-12 17:53 UTC by tarrencev

This adds support for jwt based authorization. The issuance and verification of the jwt should happen by other services (i.e. verificaiton by [envoy jwt auth](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/jwt_authn/v2alpha/config.proto), issuance by [auth0](http://auth0.com/)). Ion defines a set of claims that it enforces:

```
type RoomClaims struct {
	ID           string `json:"id,omitempty"`
	Videopublish bool   `json:"videopublish,omitempty"`
	Audiopublish bool   `json:"audiopublish,omitempty"`
}
```

This is a draft PR. Right now it is only enforcing that the claim `ID` matches the `RID` being interacted with. Will need to do some more work to support the `videopublish` and `audiopublish`. Right now it only supports one room per token. We might want to allow a list of room claims. What do you guys think?

2020-06-12 18:33 UTC, jbrady42 commented on cmd/biz/main.go
> +	signal.Init(signal.WebSocketServerConfig{
Would be good to combine these structs so all we have to do is pass in conf.Signal

2020-06-12 18:37 UTC, tarrencev commented on cmd/biz/main.go
> +	signal.Init(signal.WebSocketServerConfig{
ok i can do that. reason i didn't is cause it seems like a pattern to not pass `conf` out of `cmd`. wasn't sure if that was a pattern we wanted to stick with

2020-06-12 22:05 UTC, jbrady42 commented on cmd/biz/main.go
> +	signal.Init(signal.WebSocketServerConfig{
If `conf.Signal` was of type `signal.WebSocketServerConfig` I think it would make sense.

2020-07-31 18:50 UTC, billylindeman requested changes
https://github.com/pion/ion/compare/auth...billylindeman:auth

2020-07-31 18:50 UTC, billylindeman commented on pkg/signal/init.go
> +	panic(NewWebSocketServer(conf, in))
This should be wrapped in a `go func() { ... }`  because signal.Init() is called in an init().  Currently this is blocking so main() never runs

2020-07-31 18:50 UTC, billylindeman commented on cmd/biz/main.go
> +	signal.Init(signal.WebSocketServerConfig{
This call is currently blocking due to NewWebSocketServer being blocking (see other comment).  Because of this main never gets run

2020-10-19 09:21 UTC, adwpc commented
may i close?

2020-11-29 00:28 UTC, closed without merging