Migrate kubernetes yaml's to helm chart
ionorg/ion pull request #319
Opened 2020-07-01 23:52 UTC by billylindeman

I have converted the yaml config from `kube/` into a helm chart.  I have been testing it in Google Kubernetes Engine and it seems to work, though I suspect it will need a bit more configuration and tweaking before its completely ready.

fixes #313

2020-07-02 00:11 UTC, leewardbound commented on kube/ion/templates/deployment-sfu.yaml
> +              cpu: 250m
I know this figure came from me, just making a note -- I am certain I winged these figures originally, we will want to get a second opinion on these defaults (and/or find good practical limits via load testing), but this is sensible enough to commit; we have a strong "alpha quality" warning so I am gonna give this a :heavy_check_mark:

2020-07-02 00:17 UTC, leewardbound commented on kube/ion/values.yaml
> +replicaCount: 1
@billylindeman might be overkill, but i suggest adding a heavy paragraph disclaimer here -- "SFU relay is WIP, do not scale beyond 1 SFU" etc, as a lot of questions come from when people dive into deploying the k8s charts without consulting the readme

2020-07-02 00:24 UTC, leewardbound reviewed
I'm cool with this, gonna ask for a review from @jbrady42 first because he is definitely better k8s than me (and @tarrencev i know you mentioned wanting to try this too)

2020-07-02 00:59 UTC, leewardbound approved these changes

2020-07-02 16:33 UTC, maszhin commented on kube/ion/templates/deployment-sfu.yaml
> +          image: pionwebrtc/ion:v0.4.6
@billylindeman 

This line is missing `-sfu`
Should be `pionwebrtc/ion-sfu:v0.4.6`

2020-07-02 17:23 UTC, billylindeman commented on kube/ion/templates/deployment-sfu.yaml
> +          image: pionwebrtc/ion:v0.4.6
ah good catch! I find/replaced some stuff and this must've gotten caught in it

2020-07-02 20:33 UTC, jbrady42 requested changes
This is cool to have templated out in helm. Though honestly I prefer to work directly with the raw yaml files and potentially other tools like kustomize. We should leave the stock kube config in native yaml in another dir as an option and allow users to choose whichever they prefer.

2020-07-13 21:19 UTC, leewardbound commented
@billylindeman is this ready to merge? I'm good with it. @jbrady42 are we good?

2020-07-13 21:41 UTC, jbrady42 approved these changes
:+1:

2020-07-14 20:27 UTC, merged